trigger:
  - develop
  - staging
  - release*
  - main
pr:
  branches:
    include:
      - '*'
resources:
  repositories:
    - repository: devops
      name: BGA-DEVSECOPS/ci-templates
      type: git
      ref: refs/heads/main
      endpoint: AzureDevOpsBancoGanadero

extends:
  template: templates/ci-nodejs.yml@devops
  parameters:
    teamName: 'bg-crm'
    projectName: 'bg-crm'
    applicationName: 'authlogin-gestion-comercial'
    nodejsVersion: '20.x'