trigger:
  - develop
  - staging
  - release*
  - main

parameters:
  - name: branchOptions
    displayName: 'Source branch options'
    type: object
    default:
      - refs/heads/develop
      - refs/heads/staging
      - refs/heads/release*
      - refs/heads/main

variables:
  # Alamacena el token PAT necesario para clonar el helm repos
  - group: Repository-Token
  # URL para clonar el repositorio gitops con un token PAT
  - name: gitopsRepository
    value: 'https://$(PAT)@dev.azure.com/BancoGanadero/BGA-Internal/_git/gitops'
  # Nombre necesario para crear infra en ./infra/team/productName
  - name: team
    value: 'motorcrm'
  # [Opcional] Nombre del namespace donde está desplegado
  - name: namespace
    value: 'web-services'
  # [Opcional] Alias con el que se desplegara
  - name: appalias
    value: 'gestion-comercial-login'
  # Nombre que aloja el codigo fuente
  - name: productName
    value: 'cobranzaslogin'
  # credencial para acceso a hub (Service Connection Name)
  - name: registryCredential
    value: 'DockerHubBancoGanadero'
  # usuario con acceso
  - name: dockerUser
    value: 'bancoganadero'
  # Nombre del repositorio en el registro de contenedores
  - name: dockerRepo
    value: '$(productName)'
  # Valor del TAG para la imagen
  - name: dockerImageTAG
    value: '$(Build.BuildId).$(Build.SourceBranchName)'
  # Git Helm Charts donde encontrar $chart y almacenar la infra
  - name: helmChartsURL
    value: 'https://BancoGanadero@dev.azure.com/BancoGanadero/BGA-Internal/_git/gitops'
  # Nombre del puerto que expone el contenedor
  - name: portName
    value: 'http'
  # Numero del puerto a escuchar en el contenedor
  - name: portNumber
    value: '3000'
  # Nombre del chart a utilizar para este proyecto
  - name: chart
    value: 'simple-chart'
  # Condicion para detener (1) o continuar (0) la pipeline si existe vulnerabilidades
  - name: stopCondition
    value: '--exit-code 1 --severity HIGH,CRITICAL'
  # Para el caso de proyectos con multi stage build que dan errores
  - name: excludeIMG
    value: 'base|build'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: Ubuntu-latest
        steps:
          - script: |
              npm install jest --save-dev
              npm install --legacy-peer-deps
              npm run test:cov
            displayName: 'npm install and output coverage'

          - task: SonarQubePrepare@6
            inputs:
              SonarQube: 'SonarQube'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: '$(team)_$(productName)'
              cliProjectName: '$(team)_$(productName)'
              cliSources: '.'
              extraProperties: |
                sonar.javascript.lcov.reportPaths=./coverage/lcov.info

          - task: SonarQubeAnalyze@6

          - task: Bash@3
            displayName: 'Clean env variables'
            inputs:
              targetType: 'inline'
              script: |
                BRANCH_NAME="$(Build.SourceBranchName)"
                [ -f .env ] && cat ./cicd/env-${BRANCH_NAME%-*} > .env || echo "No tenemos .env definido"

          - task: Docker@2
            displayName: Build an image
            inputs:
              containerRegistry: '$(registryCredential)'
              repository: '$(dockerUser)/$(dockerRepo)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: '$(dockerImageTAG)'

          - task: ShellScript@2
            displayName: 'Scan dockerfile'
            inputs:
              scriptPath: scan.sh

          - task: SonarQubePublish@6
            inputs:
              pollingTimeoutSec: '300'

  - stage: Deploy_Development
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/develop'))
    variables:
      tmpPath: 'tmp/env-data-$(productName).yaml'
      scriptPath: './devsecops-bga-tpls/bash-scripts/new-project.sh'
    jobs:
      - job: deploy_with_argocd
        displayName: 'Deploy with ArgoCD'
        steps:
          - task: Bash@3
            displayName: 'Copy variables if exist'
            inputs:
              targetType: 'inline'
              script: |
                [ -f ./cicd/env-data.yaml ] && cp ./cicd/env-data.yaml /$(tmpPath) || echo 'No existe ./cicd/env-data.yaml'

          - script: 'git clone --branch main $(gitopsRepository)'
            displayName: 'Clone repository of Helms'
            workingDirectory: '$(Agent.TempDirectory)'

          - task: Bash@3
            displayName: 'Execute bash of argoCD'
            inputs:
              targetType: 'inline'
              script: |
                export team="$(team)"
                export namespace="$(namespace)"
                export appalias="$(appalias)"
                export productName="$(productName)"
                export registryCredential="$(registryCredential)"
                export dockerUser="$(dockerUser)"
                export dockerRepo="$(dockerRepo)"
                export dockerImageTAG="$(dockerImageTAG)"
                export helmChartsURL="$(helmChartsURL)"
                export portName="$(portName)"
                export portNumber="$(portNumber)"
                export chart="$(chart)"
                BRANCH_NAME="$(Build.SourceBranchName)"
                projectBranch="${BRANCH_NAME%-*}" bash $(scriptPath)
              workingDirectory: '$(Agent.TempDirectory)/gitops'

          - task: Bash@3
            displayName: 'Delete the file env temp'
            inputs:
              targetType: 'inline'
              script: |
                [ -f /$(tmpPath) ] && rm -fv /$(tmpPath) || echo 'No existe /$(tmpPath)'

  - stage: Deploy_Staging
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/staging'))
    variables:
      tmpPath: 'tmp/env-data-$(productName).yaml'
      scriptPath: './devsecops-bga-tpls/bash-scripts/new-project.sh'
    jobs:
      - job: deploy_with_argocd
        displayName: 'Deploy with ArgoCD'
        steps:
          - task: Bash@3
            displayName: 'Copy variables if exist'
            inputs:
              targetType: 'inline'
              script: |
                [ -f ./cicd/env-data.yaml ] && cp ./cicd/env-data.yaml /$(tmpPath) || echo 'No existe ./cicd/env-data.yaml'

          - script: 'git clone --branch main $(gitopsRepository)'
            displayName: 'Clone repository of Helms'
            workingDirectory: '$(Agent.TempDirectory)'

          - task: Bash@3
            displayName: 'Execute bash of argoCD'
            inputs:
              targetType: 'inline'
              script: |
                export team="$(team)"
                export namespace="$(namespace)"
                export appalias="$(appalias)"
                export productName="$(productName)"
                export registryCredential="$(registryCredential)"
                export dockerUser="$(dockerUser)"
                export dockerRepo="$(dockerRepo)"
                export dockerImageTAG="$(dockerImageTAG)"
                export helmChartsURL="$(helmChartsURL)"
                export portName="$(portName)"
                export portNumber="$(portNumber)"
                export chart="$(chart)"
                BRANCH_NAME="$(Build.SourceBranchName)"
                projectBranch="${BRANCH_NAME%-*}" bash $(scriptPath)
              workingDirectory: '$(Agent.TempDirectory)/gitops'

          - task: Bash@3
            displayName: 'Delete the file env temp'
            inputs:
              targetType: 'inline'
              script: |
                [ -f /$(tmpPath) ] && rm -fv /$(tmpPath) || echo 'No existe /$(tmpPath)'

  - stage: Deploy_PreProd
    dependsOn: Build
    condition: and(succeeded(), startsWith(variables['build.sourceBranch'], 'refs/heads/release'))
    pool:
      name: Prod_Linux_Builder
    variables:
      tmpPath: 'tmp/env-data-$(productName).yaml'
      scriptPath: './devsecops-bga-tpls/bash-scripts/new-project.sh'
    jobs:
      - job: deploy_with_argocd
        displayName: 'Deploy with ArgoCD'
        steps:
          - task: Bash@3
            displayName: 'Copy variables if exist'
            inputs:
              targetType: 'inline'
              script: |
                [ -f ./cicd/env-data.yaml ] && cp ./cicd/env-data.yaml /$(tmpPath) || echo 'No existe ./cicd/env-data.yaml'

          - script: 'git clone --branch main $(gitopsRepository)'
            displayName: 'Clone repository of Helms'
            workingDirectory: '$(Agent.TempDirectory)'

          - task: Bash@3
            displayName: 'Execute bash of argoCD'
            inputs:
              targetType: 'inline'
              script: |
                export team="$(team)"
                export namespace="$(namespace)"
                export appalias="$(appalias)"
                export productName="$(productName)"
                export registryCredential="$(registryCredential)"
                export dockerUser="$(dockerUser)"
                export dockerRepo="$(dockerRepo)"
                export dockerImageTAG="$(dockerImageTAG)"
                export helmChartsURL="$(helmChartsURL)"
                export portName="$(portName)"
                export portNumber="$(portNumber)"
                export chart="$(chart)"
                BRANCH_NAME="$(Build.SourceBranchName)"
                projectBranch="${BRANCH_NAME%-*}" bash $(scriptPath)
              workingDirectory: '$(Agent.TempDirectory)/gitops'

          - task: Bash@3
            displayName: 'Delete the file env temp'
            inputs:
              targetType: 'inline'
              script: |
                [ -f /$(tmpPath) ] && rm -fv /$(tmpPath) || echo 'No existe /$(tmpPath)'

  - stage: Deploy_Prod
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    pool:
      name: Prod_Linux_Builder
    variables:
      tmpPath: 'tmp/env-data-$(productName).yaml'
      scriptPath: './devsecops-bga-tpls/bash-scripts/new-project.sh'
    jobs:
      - job: deploy_with_argocd
        displayName: 'Deploy with ArgoCD'
        steps:
          - task: Bash@3
            displayName: 'Copy variables if exist'
            inputs:
              targetType: 'inline'
              script: |
                [ -f ./cicd/env-data.yaml ] && cp ./cicd/env-data.yaml /$(tmpPath) || echo 'No existe ./cicd/env-data.yaml'

          - script: 'git clone --branch main $(gitopsRepository)'
            displayName: 'Clone repository of Helms'
            workingDirectory: '$(Agent.TempDirectory)'

          - task: Bash@3
            displayName: 'Execute bash of argoCD'
            inputs:
              targetType: 'inline'
              script: |
                export team="$(team)"
                export namespace="$(namespace)"
                export appalias="$(appalias)"
                export productName="$(productName)"
                export registryCredential="$(registryCredential)"
                export dockerUser="$(dockerUser)"
                export dockerRepo="$(dockerRepo)"
                export dockerImageTAG="$(dockerImageTAG)"
                export helmChartsURL="$(helmChartsURL)"
                export portName="$(portName)"
                export portNumber="$(portNumber)"
                export chart="$(chart)"
                BRANCH_NAME="$(Build.SourceBranchName)"
                projectBranch="${BRANCH_NAME%-*}" bash $(scriptPath)
              workingDirectory: '$(Agent.TempDirectory)/gitops'

          - task: Bash@3
            displayName: 'Delete the file env temp'
            inputs:
              targetType: 'inline'
              script: |
                [ -f /$(tmpPath) ] && rm -fv /$(tmpPath) || echo 'No existe /$(tmpPath)'
